-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spqr]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Spqr.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open spqr

/-- [core::array::from_fn]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 109:0-111:52
    Name pattern: [core::array::from_fn] -/
@[rust_fun "core::array::from_fn"]
axiom core.array.from_fn
  {T : Type} {F : Type} (N : Std.Usize) (opsfunctionFnMutFTupleUsizeTInst :
  core.ops.function.FnMut F Std.Usize T) :
  F → Result (Array T N)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2466:4-2473:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish] -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish"]
axiom core.fmt.Formatter.debug_struct_field2_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Display for &0 (T)}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2865:12-2865:58
    Name pattern: [core::fmt::{core::fmt::Display<&'0 @T>}::fmt] -/
@[rust_fun "core::fmt::{core::fmt::Display<&'0 @T>}::fmt"]
axiom Shared0T.Insts.CoreFmtDisplay.fmt
  {T : Type} (DisplayInst : core.fmt.Display T) :
  T → core.fmt.Formatter → Result ((core.result.Result Unit core.fmt.Error)
    × core.fmt.Formatter)

/-- [core::hint::black_box]:
    Source: '/rustc/library/core/src/hint.rs', lines 490:0-490:40
    Name pattern: [core::hint::black_box] -/
@[rust_fun "core::hint::black_box"]
axiom core.hint.black_box {T : Type} : T → Result T

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 79:4-79:64
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::next] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::next"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.next
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.enumerate.Enumerate I → Result ((Option (Std.Usize ×
    Clause0_Item)) × (core.iter.adapters.enumerate.Enumerate I))

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::collect] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::collect"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.collect
  {I : Type} {B : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item)
  (traitscollectFromIteratorBPairUsizeClause0_ItemInst :
  core.iter.traits.collect.FromIterator B (Std.Usize × Clause0_Item)) :
  core.iter.adapters.enumerate.Enumerate I → Result B

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::enumerate]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::enumerate] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::enumerate"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.enumerate
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.adapters.enumerate.Enumerate I → Result
    (core.iter.adapters.enumerate.Enumerate
    (core.iter.adapters.enumerate.Enumerate I))

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::map]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::map] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::map"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.map
  {I : Type} {B : Type} {F : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTuplePairUsizeClause0_ItemBInst :
  core.ops.function.FnMut F (Std.Usize × Clause0_Item) B) :
  core.iter.adapters.enumerate.Enumerate I → F → Result
    (core.iter.adapters.map.Map (core.iter.adapters.enumerate.Enumerate I) F)

/-- [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::zip]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::zip] -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::zip"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.zip
  {I : Type} {U : Type} {Clause0_Item : Type} {Clause1_Item : Type}
  {Clause1_IntoIter : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item)
  (traitscollectIntoIteratorInst : core.iter.traits.collect.IntoIterator U
  Clause1_Item Clause1_IntoIter) :
  core.iter.adapters.enumerate.Enumerate I → U → Result
    (core.iter.adapters.zip.Zip (core.iter.adapters.enumerate.Enumerate I)
    Clause1_IntoIter)

/-- [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect] -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {B : Type} {I : Type} {F : Type} {B1 : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (traitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator B1 B) :
  core.iter.adapters.map.Map I F → Result B1

/-- [core::iter::adapters::zip::{core::iter::traits::iterator::Iterator<(Clause0_Item, Clause1_Item)> for core::iter::adapters::zip::Zip<A, B>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/zip.rs', lines 84:4-84:44
    Name pattern: [core::iter::adapters::zip::{core::iter::traits::iterator::Iterator<core::iter::adapters::zip::Zip<@A, @B>, (@Clause0_Item, @Clause1_Item)>}::next] -/
@[rust_fun
  "core::iter::adapters::zip::{core::iter::traits::iterator::Iterator<core::iter::adapters::zip::Zip<@A, @B>, (@Clause0_Item, @Clause1_Item)>}::next"]
axiom core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair.next
  {A : Type} {B : Type} {Clause0_Item : Type} {Clause1_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator A
  Clause0_Item) (traitsiteratorIteratorInst1 :
  core.iter.traits.iterator.Iterator B Clause1_Item) :
  core.iter.adapters.zip.Zip A B → Result ((Option (Clause0_Item ×
    Clause1_Item)) × (core.iter.adapters.zip.Zip A B))

/-- [core::iter::range::{core::iter::range::Step for i32}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 340:16-340:74
    Name pattern: [core::iter::range::{core::iter::range::Step<i32>}::backward_checked] -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<i32>}::backward_checked"]
axiom I32.Insts.CoreIterRangeStep.backward_checked
  : Std.I32 → Std.Usize → Result (Option Std.I32)

/-- [core::iter::range::{core::iter::range::Step for i32}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 319:16-319:73
    Name pattern: [core::iter::range::{core::iter::range::Step<i32>}::forward_checked] -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<i32>}::forward_checked"]
axiom I32.Insts.CoreIterRangeStep.forward_checked
  : Std.I32 → Std.Usize → Result (Option Std.I32)

/-- [core::iter::range::{core::iter::range::Step for i32}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 304:16-304:84
    Name pattern: [core::iter::range::{core::iter::range::Step<i32>}::steps_between] -/
@[rust_fun "core::iter::range::{core::iter::range::Step<i32>}::steps_between"]
axiom I32.Insts.CoreIterRangeStep.steps_between
  : Std.I32 → Std.I32 → Result (Std.Usize × (Option Std.Usize))

/-- [core::iter::traits::iterator::Iterator::zip]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 626:4-629:24
    Name pattern: [core::iter::traits::iterator::Iterator::zip] -/
@[rust_fun "core::iter::traits::iterator::Iterator::zip"]
axiom core.iter.traits.iterator.Iterator.zip.default
  {Self : Type} {U : Type} {Clause0_Item : Type} {Clause1_Item : Type}
  {Clause1_IntoIter : Type} (IteratorInst : core.iter.traits.iterator.Iterator
  Self Clause0_Item) (collectIntoIteratorInst :
  core.iter.traits.collect.IntoIterator U Clause1_Item Clause1_IntoIter) :
  Self → U → Result (core.iter.adapters.zip.Zip Self Clause1_IntoIter)

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 789:4-792:34
    Name pattern: [core::iter::traits::iterator::Iterator::map] -/
@[rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::traits::iterator::Iterator::enumerate]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 1005:4-1007:20
    Name pattern: [core::iter::traits::iterator::Iterator::enumerate] -/
@[rust_fun "core::iter::traits::iterator::Iterator::enumerate"]
axiom core.iter.traits.iterator.Iterator.enumerate.default
  {Self : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) :
  Self → Result (core.iter.adapters.enumerate.Enumerate Self)

/-- [core::option::{core::option::Option<T>}::as_ref]:
    Source: '/rustc/library/core/src/option.rs', lines 744:4-744:44
    Name pattern: [core::option::{core::option::Option<@T>}::as_ref] -/
@[rust_fun "core::option::{core::option::Option<@T>}::as_ref"]
axiom core.option.Option.as_ref {T : Type} : Option T → Result (Option T)

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch] -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual] -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [core::slice::index::{core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFull}::index_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 660:4-660:51
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::index_mut] -/
@[rust_fun
  "core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::index_mut"]
axiom
  core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.index_mut
  {T : Type} :
  core.ops.range.RangeFull → Slice T → Result ((Slice T) × (Slice T →
    Slice T))

/-- [core::slice::index::{core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFull}::index]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 655:4-655:39
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::index] -/
@[rust_fun
  "core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::index"]
axiom core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.index
  {T : Type} : core.ops.range.RangeFull → Slice T → Result (Slice T)

/-- [core::slice::index::{core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFull}::get_unchecked_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 650:4-650:66
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get_unchecked_mut] -/
@[rust_fun
  "core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get_unchecked_mut"]
axiom
  core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get_unchecked_mut
  {T : Type} :
  core.ops.range.RangeFull → MutRawPtr (Slice T) → Result (MutRawPtr (Slice
    T))

/-- [core::slice::index::{core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFull}::get_unchecked]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 645:4-645:66
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get_unchecked] -/
@[rust_fun
  "core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get_unchecked"]
axiom
  core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get_unchecked
  {T : Type} :
  core.ops.range.RangeFull → ConstRawPtr (Slice T) → Result (ConstRawPtr
    (Slice T))

/-- [core::slice::index::{core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFull}::get_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 640:4-640:57
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get_mut] -/
@[rust_fun
  "core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get_mut"]
axiom core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get_mut
  {T : Type} :
  core.ops.range.RangeFull → Slice T → Result ((Option (Slice T)) ×
    (Option (Slice T) → Slice T))

/-- [core::slice::index::{core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFull}::get]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 635:4-635:45
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get] -/
@[rust_fun
  "core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFull, [@T], [@T]>}::get"]
axiom core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get
  {T : Type} :
  core.ops.range.RangeFull → Slice T → Result (Option (Slice T))

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::collect]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::collect] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::collect"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.collect
  {T : Type} {B : Type} (itertraitscollectFromIteratorBSharedATInst :
  core.iter.traits.collect.FromIterator B T) :
  core.slice.iter.Iter T → Result B

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::map]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::map] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::map"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map
  {T : Type} {B : Type} {F : Type} (opsfunctionFnMutFTupleSharedATBInst :
  core.ops.function.FnMut F T B) :
  core.slice.iter.Iter T → F → Result (core.iter.adapters.map.Map
    (core.slice.iter.Iter T) F)

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a (T)> for core::slice::iter::Iter<'a, T>}::zip]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::zip] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::zip"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.zip
  {T : Type} {U : Type} {Clause0_Item : Type} {Clause0_IntoIter : Type}
  (itertraitscollectIntoIteratorInst : core.iter.traits.collect.IntoIterator U
  Clause0_Item Clause0_IntoIter) :
  core.slice.iter.Iter T → U → Result (core.iter.adapters.zip.Zip
    (core.slice.iter.Iter T) Clause0_IntoIter)

/-- [core::slice::iter::{core::iter::traits::collect::IntoIterator<&'a (T), core::slice::iter::Iter<'a, T>> for &'a ([T])}::into_iter]:
    Source: '/rustc/library/core/src/slice/iter.rs', lines 25:4-25:37
    Name pattern: [core::slice::iter::{core::iter::traits::collect::IntoIterator<&'a [@T], &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::collect::IntoIterator<&'a [@T], &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter"]
axiom
  SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
  {T : Type} : Slice T → Result (core.slice.iter.Iter T)

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a ([T])> for core::slice::iter::ChunksExact<'a, T>}::collect]:
    Source: '/rustc/library/core/src/slice/iter.rs', lines 1892:0-1892:43
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::ChunksExact<'a, @T>, &'a [@T]>}::collect] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::ChunksExact<'a, @T>, &'a [@T]>}::collect"]
axiom
  core.slice.iter.ChunksExact.Insts.CoreIterTraitsIteratorIteratorSharedASlice.collect
  {T : Type} {B : Type} (itertraitscollectFromIteratorBSharedASliceInst :
  core.iter.traits.collect.FromIterator B (Slice T)) :
  core.slice.iter.ChunksExact T → Result B

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a ([T])> for core::slice::iter::ChunksExact<'a, T>}::map]:
    Source: '/rustc/library/core/src/slice/iter.rs', lines 1892:0-1892:43
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::ChunksExact<'a, @T>, &'a [@T]>}::map] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::ChunksExact<'a, @T>, &'a [@T]>}::map"]
axiom
  core.slice.iter.ChunksExact.Insts.CoreIterTraitsIteratorIteratorSharedASlice.map
  {T : Type} {B : Type} {F : Type} (opsfunctionFnMutFTupleSharedASliceBInst :
  core.ops.function.FnMut F (Slice T) B) :
  core.slice.iter.ChunksExact T → F → Result (core.iter.adapters.map.Map
    (core.slice.iter.ChunksExact T) F)

/-- [core::slice::iter::{core::iter::traits::iterator::Iterator<&'a ([T])> for core::slice::iter::ChunksExact<'a, T>}::zip]:
    Source: '/rustc/library/core/src/slice/iter.rs', lines 1892:0-1892:43
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::ChunksExact<'a, @T>, &'a [@T]>}::zip] -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::ChunksExact<'a, @T>, &'a [@T]>}::zip"]
axiom
  core.slice.iter.ChunksExact.Insts.CoreIterTraitsIteratorIteratorSharedASlice.zip
  {T : Type} {U : Type} {Clause0_Item : Type} {Clause0_IntoIter : Type}
  (itertraitscollectIntoIteratorInst : core.iter.traits.collect.IntoIterator U
  Clause0_Item Clause0_IntoIter) :
  core.slice.iter.ChunksExact T → U → Result (core.iter.adapters.zip.Zip
    (core.slice.iter.ChunksExact T) Clause0_IntoIter)

/-- [core::slice::{[T]}::clone_from_slice]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 4254:4-4256:44
    Name pattern: [core::slice::{[@T]}::clone_from_slice] -/
@[rust_fun "core::slice::{[@T]}::clone_from_slice"]
axiom core.slice.Slice.clone_from_slice
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Slice T → Slice T → Result (Slice T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::remove]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2276:4-2276:47
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::remove] -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::remove"]
axiom alloc.vec.Vec.remove
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (T × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2956:4-2956:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty] -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [sorted_vec::{core::clone::Clone for sorted_vec::SortedSet<T>[TraitClause@1]}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 38:9-38:14
    Name pattern: [sorted_vec::{core::clone::Clone<sorted_vec::SortedSet<@T>>}::clone] -/
@[rust_fun
  "sorted_vec::{core::clone::Clone<sorted_vec::SortedSet<@T>>}::clone"]
axiom sorted_vec.SortedSet.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecmpOrdInst :
  core.cmp.Ord T) :
  sorted_vec.SortedSet corecmpOrdInst → Result (sorted_vec.SortedSet
    corecmpOrdInst)

/-- [sorted_vec::{core::ops::deref::Deref<alloc::vec::Vec<T>> for sorted_vec::SortedVec<T>[TraitClause@0]}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 309:2-309:30
    Name pattern: [sorted_vec::{core::ops::deref::Deref<sorted_vec::SortedVec<@T>, alloc::vec::Vec<@T>>}::deref] -/
@[rust_fun
  "sorted_vec::{core::ops::deref::Deref<sorted_vec::SortedVec<@T>, alloc::vec::Vec<@T>>}::deref"]
axiom sorted_vec.SortedVec.Insts.CoreOpsDerefDerefVec.deref
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) :
  sorted_vec.SortedVec corecmpOrdInst → Result (alloc.vec.Vec T)

/-- [sorted_vec::{sorted_vec::SortedSet<T>[TraitClause@0]}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 347:2-347:22
    Name pattern: [sorted_vec::{sorted_vec::SortedSet<@T>}::new] -/
@[rust_fun "sorted_vec::{sorted_vec::SortedSet<@T>}::new"]
axiom sorted_vec.SortedSet.new
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) :
  Result (sorted_vec.SortedSet corecmpOrdInst)

/-- [sorted_vec::{sorted_vec::SortedSet<T>[TraitClause@0]}::with_capacity]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 351:2-351:49
    Name pattern: [sorted_vec::{sorted_vec::SortedSet<@T>}::with_capacity] -/
@[rust_fun "sorted_vec::{sorted_vec::SortedSet<@T>}::with_capacity"]
axiom sorted_vec.SortedSet.with_capacity
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) :
  Std.Usize → Result (sorted_vec.SortedSet corecmpOrdInst)

/-- [sorted_vec::{sorted_vec::SortedSet<T>[TraitClause@0]}::push]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 392:2-392:58
    Name pattern: [sorted_vec::{sorted_vec::SortedSet<@T>}::push] -/
@[rust_fun "sorted_vec::{sorted_vec::SortedSet<@T>}::push"]
axiom sorted_vec.SortedSet.push
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) :
  sorted_vec.SortedSet corecmpOrdInst → T → Result ((Std.Usize × (Option
    T)) × (sorted_vec.SortedSet corecmpOrdInst))

/-- [sorted_vec::{core::ops::deref::Deref<sorted_vec::SortedVec<T>[TraitClause@0]> for sorted_vec::SortedSet<T>[TraitClause@0]}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 543:2-543:36
    Name pattern: [sorted_vec::{core::ops::deref::Deref<sorted_vec::SortedSet<@T>, sorted_vec::SortedVec<@T>>}::deref] -/
@[rust_fun
  "sorted_vec::{core::ops::deref::Deref<sorted_vec::SortedSet<@T>, sorted_vec::SortedVec<@T>>}::deref"]
axiom sorted_vec.SortedSet.Insts.CoreOpsDerefDerefSortedVec.deref
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) :
  sorted_vec.SortedSet corecmpOrdInst → Result (sorted_vec.SortedVec
    corecmpOrdInst)

/-- [thiserror::display::{thiserror::display::AsDisplay<'a, &'a (T)> for &1 (T)}::as_display]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thiserror-2.0.12/src/display.rs', lines 20:4-20:43
    Name pattern: [thiserror::display::{thiserror::display::AsDisplay<'a, &'0 @T, &'a @T>}::as_display] -/
@[rust_fun
  "thiserror::display::{thiserror::display::AsDisplay<'a, &'0 @T, &'a @T>}::as_display"]
axiom Shared0T.Insts.ThiserrorDisplayAsDisplayASharedAT.as_display
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result T

/-- [spqr::encoding::gf::{core::ops::arith::MulAssign<&0 (spqr::encoding::gf::GF16)> for spqr::encoding::gf::GF16}::mul_assign]:
    Source: 'src/encoding/gf.rs', lines 127:4-137:5 -/
axiom encoding.gf.GF16.Insts.CoreOpsArithMulAssignShared0GF16.mul_assign
  : encoding.gf.GF16 → encoding.gf.GF16 → Result encoding.gf.GF16

/-- [spqr::encoding::gf::mul2_u16]:
    Source: 'src/encoding/gf.rs', lines 216:0-225:1 -/
axiom encoding.gf.mul2_u16
  : Std.U16 → Std.U16 → Std.U16 → Result (Std.U16 × Std.U16)

/-- [spqr::encoding::polynomial::{spqr::encoding::Decoder for spqr::encoding::polynomial::PolyDecoder}::decoded_message]:
    Source: 'src/encoding/polynomial.rs', lines 883:4-935:5 -/
axiom encoding.polynomial.PolyDecoder.Insts.SpqrEncodingDecoder.decoded_message
  : encoding.polynomial.PolyDecoder → Result (Option (alloc.vec.Vec Std.U8))

