-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spqr]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/-- [core::iter::adapters::zip::Zip]
    Source: '/rustc/library/core/src/iter/adapters/zip.rs', lines 15:0-15:20
    Name pattern: [core::iter::adapters::zip::Zip] -/
@[rust_type "core::iter::adapters::zip::Zip"]
axiom core.iter.adapters.zip.Zip (A : Type) (B : Type) : Type

/-- [sorted_vec::SortedVec]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 27:0-27:30
    Name pattern: [sorted_vec::SortedVec] -/
@[rust_type "sorted_vec::SortedVec"]
axiom sorted_vec.SortedVec {T : Type} (corecmpOrdInst : core.cmp.Ord T) : Type

/-- [sorted_vec::SortedSet]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sorted-vec-0.8.6/src/lib.rs', lines 39:0-39:30
    Name pattern: [sorted_vec::SortedSet] -/
@[rust_type "sorted_vec::SortedSet"]
axiom sorted_vec.SortedSet {T : Type} (corecmpOrdInst : core.cmp.Ord T) : Type

