-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spqr]: type definitions
import Aeneas
import Spqr.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace spqr

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 77:0-77:31
    Name pattern: [core::ops::arith::Add] -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 190:0-190:31
    Name pattern: [core::ops::arith::Sub] -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 324:0-324:31
    Name pattern: [core::ops::arith::Mul] -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 462:0-462:31
    Name pattern: [core::ops::arith::Div] -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 769:0-769:37
    Name pattern: [core::ops::arith::AddAssign] -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::SubAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 840:0-840:37
    Name pattern: [core::ops::arith::SubAssign] -/
@[rust_trait "core::ops::arith::SubAssign"]
structure core.ops.arith.SubAssign (Self : Type) (Rhs : Type) where
  sub_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::MulAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 902:0-902:37
    Name pattern: [core::ops::arith::MulAssign] -/
@[rust_trait "core::ops::arith::MulAssign"]
structure core.ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::DivAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 964:0-964:37
    Name pattern: [core::ops::arith::DivAssign] -/
@[rust_trait "core::ops::arith::DivAssign"]
structure core.ops.arith.DivAssign (Self : Type) (Rhs : Type) where
  div_assign : Self → Rhs → Result Self

/-- [core::ops::range::RangeFull]
    Source: '/rustc/library/core/src/ops/range.rs', lines 44:0-44:20
    Name pattern: [core::ops::range::RangeFull] -/
@[reducible, rust_type "core::ops::range::RangeFull"]
def core.ops.range.RangeFull := Unit

/-- [spqr::proto::pq_ratchet::PolynomialEncoder]
    Source: '/home/oliver/Projects/Verification/SparsePostQuantumRatchet/target/x86_64-unknown-linux-gnu/debug/build/spqr-026a0a30401f68eb/out/signal.proto.pq_ratchet.rs', lines 3:0-13:1 -/
structure proto.pq_ratchet.PolynomialEncoder where
  idx : Std.U32
  pts : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  polys : alloc.vec.Vec (alloc.vec.Vec Std.U8)

/-- [spqr::proto::pq_ratchet::PolynomialDecoder]
    Source: '/home/oliver/Projects/Verification/SparsePostQuantumRatchet/target/x86_64-unknown-linux-gnu/debug/build/spqr-026a0a30401f68eb/out/signal.proto.pq_ratchet.rs', lines 15:0-24:1 -/
structure proto.pq_ratchet.PolynomialDecoder where
  pts_needed : Std.U32
  polys : Std.U32
  pts : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  is_complete : Bool

/-- [spqr::encoding::gf::GF16]
    Source: 'src/encoding/gf.rs', lines 16:0-18:1 -/
structure encoding.gf.GF16 where
  value : Std.U16

/-- [spqr::encoding::polynomial::PolynomialError]
    Source: 'src/encoding/polynomial.rs', lines 13:0-20:1 -/
@[discriminant isize]
inductive encoding.polynomial.PolynomialError where
| MessageLengthEven : encoding.polynomial.PolynomialError
| MessageLengthTooLong : encoding.polynomial.PolynomialError
| SerializationInvalid : encoding.polynomial.PolynomialError

/-- [spqr::encoding::polynomial::Pt]
    Source: 'src/encoding/polynomial.rs', lines 26:0-29:1 -/
structure encoding.polynomial.Pt where
  x : encoding.gf.GF16
  y : encoding.gf.GF16

/-- [spqr::encoding::polynomial::Poly]
    Source: 'src/encoding/polynomial.rs', lines 79:0-88:1 -/
structure encoding.polynomial.Poly where
  coefficients : alloc.vec.Vec encoding.gf.GF16

/-- [spqr::encoding::polynomial::PolyConst]
    Source: 'src/encoding/polynomial.rs', lines 353:0-355:1 -/
structure encoding.polynomial.PolyConst (N : Std.Usize) where
  coefficients : Array encoding.gf.GF16 N

/-- [spqr::encoding::polynomial::const_polys_to_polys::closure]
    Source: 'src/encoding/polynomial.rs', lines 462:19-462:34 -/
@[reducible]
def encoding.polynomial.const_polys_to_polys.closure (N : Std.Usize) := Unit

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::Poly}::from_complete_points::closure#1]
    Source: 'src/encoding/polynomial.rs', lines 319:25-319:75 -/
@[reducible]
def encoding.polynomial.Poly.from_complete_points.closure_1 :=
  alloc.vec.Vec encoding.polynomial.Pt

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::Poly}::from_complete_points::closure]
    Source: 'src/encoding/polynomial.rs', lines 312:25-315:21 -/
@[reducible]
def encoding.polynomial.Poly.from_complete_points.closure := Unit

/-- [spqr::encoding::polynomial::Point]
    Source: 'src/encoding/polynomial.rs', lines 510:0-513:1 -/
structure encoding.polynomial.Point where
  value : alloc.vec.Vec encoding.gf.GF16

/-- [spqr::encoding::polynomial::EncoderState]
    Source: 'src/encoding/polynomial.rs', lines 516:0-522:1 -/
@[discriminant isize]
inductive encoding.polynomial.EncoderState where
| Points :
  Array encoding.polynomial.Point 16#usize →
  encoding.polynomial.EncoderState
| Polys :
  Array encoding.polynomial.Poly 16#usize →
  encoding.polynomial.EncoderState

/-- [spqr::encoding::polynomial::PolyEncoder]
    Source: 'src/encoding/polynomial.rs', lines 525:0-528:1 -/
structure encoding.polynomial.PolyEncoder where
  idx : Std.U32
  s : encoding.polynomial.EncoderState

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::from_pb::closure#1]
    Source: 'src/encoding/polynomial.rs', lines 598:66-598:83 -/
@[reducible]
def encoding.polynomial.PolyEncoder.from_pb.closure_1 := Unit

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::from_pb::closure]
    Source: 'src/encoding/polynomial.rs', lines 579:47-581:13 -/
@[reducible]
def encoding.polynomial.PolyEncoder.from_pb.closure := Unit

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::point_at::closure#1]
    Source: 'src/encoding/polynomial.rs', lines 628:25-631:21 -/
@[reducible]
def encoding.polynomial.PolyEncoder.point_at.closure_1 := Unit

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::point_at::closure]
    Source: 'src/encoding/polynomial.rs', lines 622:68-622:85 -/
@[reducible]
def encoding.polynomial.PolyEncoder.point_at.closure := Unit

/-- [spqr::encoding::EncodingError]
    Source: 'src/encoding.rs', lines 9:0-16:1 -/
@[discriminant isize]
inductive encoding.EncodingError where
| PolynomialError :
  encoding.polynomial.PolynomialError →
  encoding.EncodingError
| ChunkIndexDecodingError : encoding.EncodingError
| ChunkDataDecodingError : encoding.EncodingError

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::encode_bytes_base::closure]
    Source: 'src/encoding/polynomial.rs', lines 663:63-665:9 -/
@[reducible]
def encoding.polynomial.PolyEncoder.encode_bytes_base.closure := Slice Std.U8

/-- [spqr::encoding::Chunk]
    Source: 'src/encoding.rs', lines 25:0-28:1 -/
structure encoding.Chunk where
  index : Std.U16
  data : Array Std.U8 32#usize

/-- Trait declaration: [spqr::encoding::Encoder]
    Source: 'src/encoding.rs', lines 31:0-37:1 -/
structure encoding.Encoder (Self : Type) where
  encode_bytes : Slice Std.U8 → Result (core.result.Result Self
    encoding.EncodingError)
  next_chunk : Self → Result (encoding.Chunk × Self)

/-- [spqr::encoding::polynomial::PolyDecoder]
    Source: 'src/encoding/polynomial.rs', lines 729:0-748:1 -/
structure encoding.polynomial.PolyDecoder where
  pts_needed : Std.Usize
  pts : Array (sorted_vec.SortedSet encoding.polynomial.Pt.Insts.CoreCmpOrd)
    16#usize
  is_complete : Bool

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyDecoder}::new_with_poly_count::closure]
    Source: 'src/encoding/polynomial.rs', lines 775:38-775:58 -/
@[reducible]
def encoding.polynomial.PolyDecoder.new_with_poly_count.closure := Unit

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyDecoder}::from_pb::closure]
    Source: 'src/encoding/polynomial.rs', lines 808:47-808:67 -/
@[reducible]
def encoding.polynomial.PolyDecoder.from_pb.closure := Unit

/-- Trait declaration: [spqr::encoding::Decoder]
    Source: 'src/encoding.rs', lines 40:0-47:1 -/
structure encoding.Decoder (Self : Type) where
  new : Std.Usize → Result (core.result.Result Self encoding.EncodingError)
  add_chunk : Self → encoding.Chunk → Result Self
  decoded_message : Self → Result (Option (alloc.vec.Vec Std.U8))

/-- [spqr::serialize::Error]
    Source: 'src/serialize.rs', lines 7:0-12:1 -/
@[discriminant isize]
inductive serialize.Error where
| Deserialization : serialize.Error
| EncodingDecoding : serialize.Error

end spqr
